apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-novels-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai-novels.example.com
      secretName: ai-novels-tls
  rules:
    - host: ai-novels.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ai-novels-backend
                port:
                  number: 8004
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-novels-frontend
                port:
                  number: 80
